app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo

class LoginForm(FlaskForm):
    username = StringField('Enter your username', validators=[DataRequired()])
    password = PasswordField('Enter your password', validators=[DataRequired()])
    submit =SubmitField('submit')

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    idno = StringField('Id no', validators=[DataRequired()])
    role = SelectField('Role', choices=[('admin','Admin'), ('librarian', 'Librarian'), ('student', 'Student')])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register')

class ResetEmail2(FlaskForm):
    username = StringField('New username', validators=[DataRequired()])
    password = PasswordField('New password', validators=[DataRequired(), EqualTo('password2', message='passwords must match')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Reset')

class ResetEmail(FlaskForm):
    email = StringField('Enter your email', validators=[DataRequired(), Email()])
    submit = SubmitField('Reset')

app/main/__init__.py
"""
register main as a blueprint
"""
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')
from . import views

app/main/views.py
from flask import Flask, render_template, redirect, url_for, session, flash, current_app
from .forms import LoginForm, RegisterForm, ResetEmail, ResetEmail2
from . import main
from app import db, login_manager
from app.models import User
from flask_login import login_user, logout_user, current_user, login_required
from ..emails import send_email
from itsdangerous import URLSafeTimedSerializer
from werkzeug.security import generate_password_hash

@main.route('/', methods=['GET', 'POST'])
def index():
        return render_template('index.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()

        if user and user.verify_password(password):
            login_user(user)
            if user.role == 'admin':
                flash("logged in as admin")
                return redirect(url_for('main.dashboard'))
            elif user.role == 'librarian':
                return redirect(url_for('main.dashboard'))
                flash("logged in as librarian")
            else:
                return redirect(url_for('main.dashboard'))
                flash("logged in as student")
            return redirect(url_for('main.index'))
        else:
            flash('Invalid username or password')
    return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data
        IDno = form.idno.data
        role = form.role.data

        user = User.query.filter_by(username=username).first()
        if not user:
            user = User(username, email, password, IDno, role)
            db.session.add(user)
            db.session.commit()
            flash('user registered successfully')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

@main.route('/reset', methods=['GET', 'POST'])
def resetEmail():
    """
    this function will handle sending of email
    after the user has entered their email
    """
    form = ResetEmail()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()
        token = user.generate_signed_token()
        send_email(user.email, 'Reset Your Email', 'email/resetEmail', user=user, token=token)
        flash('A reset email has been sent to you by email')
        return redirect(url_for('main.index'))
    return render_template('resetEmail.html', form=form)

@main.route('/resetEmail/<token>', methods=['GET', 'POST'])
def reset(token):
    """
    this will handle the logic that
    happens when the user clicks the link
    on the recieved mail
    """
    form = ResetEmail2()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        data = s.loads(token)
        user = User.query.filter_by(email=data).first()
        if not user:
            flash('The link is Invalid or has Expired')
            return redirect(url_for('main.reset'))
        user.username = username
        user.password = generate_password_hash(password)
        db.session.add(user)
        db.session.commit()
        flash('Password and username updated successfully')
        return redirect(url_for('main.login'))

    return render_template('resetEmail2.html', form=form)

@main.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    """
    This will define the route that
    a user takes if their role is admin when logging in
    """
    return render_template('dashboard.html')

app/main/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">LMS</a>
		</div>

		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="{{ url_for('main.index') }}">Home</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
				<li><a href="{{ url_for('main.dashboard') }}">Profile</a></li>
				<li><a href="{{ url_for('main.logout') }}">Logout</a></li>
				<li><a href="/">Change Password</a></li>
				{% else %}
				<li><a href="/">Login</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="container">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{{ message }}
	</div>
	{% endfor %}
	{% block page_content %}{% endblock %}
</div>
{% endblock %}

app/main/templates/dashboard.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}LMS - Dashboard{% endblock %}

{% block page_content %}
<div class="container">
	<div class="page-header">
		{% if current_user.role=="admin" %}
			<h2>THE LMS ADMIN</h2>
		{% elif current_user.role=="librarian" %}
			<h2>THE LMS LIBRARIAN</h2>
		{% else %}
			<h2>THE LMS STUDENT</h2>
		{% endif %}
	</div>
	<div class="row justify-content-centre">

	</div>
</div>
{% endblock %}

app/main/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}LMS - Login{% endblock %}

{% block page_content %}
<div class="container">
	<div class="page-header">
		<h2>THE LMS</h2>
	</div>
	<div class="row justify-content-centre">
		<div class="col-lg-5">
			<h5>New member?<a href="{{ url_for('main.register') }}">Sign up</a></h5>
			{{ wtf.quick_form(form) }}
			<h5>Forgot Username/Password?<a href="{{ url_for('main.reset') }}">Reset</a></h5>
		</div>

	</div>
</div>
{% endblock %}